### PR TITLE
Adding compatibility between url domain type and MX records

### PR DESCRIPTION
**Pull request by Mazamazine**
Modifications tested on a VM.
Run of alternc.install afterward went without trouble, and did the change properly.
Issue opened: https://github.com/AlternC/AlternC/issues/428

### CODE REVIEW

**Comment by kienanstewart** [comment]
In the SQL update, instead of `UPDATE domaines_type SET compatibility = 'txt,defmx,defmx2,mx,mx2' WHERE name = 'url';`, I would recommend using a query that appends 'mx,mx2' to the existing value in case some folks have made changes to the compatibility for their own needs (eg. custom hosts, etc.)

Something like, `UPDATE domaines_type SET compatibility = CONCAT(compatibility, ",mx,mx2") WHERE ....`

**Comment by Mazamazine** [comment]
Good point, I'll make the change.
We may have duplicates but it won't cause any trouble.

**Comment by Mazamazine** [comment]
I'm sort of uncomfortable with the idea of duplicating mx and mx2. It's a bit confusing.
I suggest using two queries like this to avoid it. Does it make sense?

`UPDATE domaines_type SET compatibility=CONCAT_WS(',', compatibility, 'mx') WHERE name='url' AND compatibility NOT LIKE '%,mx%' AND compatibility NOT LIKE 'mx,%';`

`UPDATE domaines_type SET compatibility=CONCAT_WS(',', compatibility, 'mx2') WHERE name='url' AND compatibility NOT LIKE '%,mx2%' AND compatibility NOT LIKE 'mx2,%';`

**Comment by kienanstewart** [comment]
> `UPDATE domaines_type SET compatibility=CONCAT_WS(',', compatibility, 'mx') WHERE name='url' AND compatibility NOT LIKE '%,mx%' AND compatibility NOT LIKE 'mx,%';`
> 
> `UPDATE domaines_type SET compatibility=CONCAT_WS(',', compatibility, 'mx2') WHERE name='url' AND compatibility NOT LIKE '%,mx2%' AND compatibility NOT LIKE 'mx2,%';`

It's a good point to not duplicate mx or mx2 if they are already present; however, the implementation suggested isn't complete. Those queries only match if `mx2` is at the start or end of the compatibility string but not the middle. It can be done with one condition: `compatibility NOT LIKE '%mx2%'`. In the case of `mx`, you need to make sure it doesn't match `mx2`. 

Edit: Nvm, re-reading them it should be OK; although it would be nice to simplify them if possible

**Comment by Mazamazine** [comment]
Well, I have not so much ideas to simplify that.
I tried using CASE / WHEN which I wasn't aware even existed but the way it works doesn't make it that simple due to the required use of LIKE.
Besides having it in one query, it's not that much prettier / readable and is way longer to execute.

**Comment by kienanstewart** [comment]
thanks for having a look at alternatives even if it didn't pan out.

**Pull request merged**
